apps/costumer/urls.py
from django.urls import path

from .views import CostumerCreation, CostumerLogin, CostumerLogout

app_name = 'costumer'

urlpatterns = [
    path('', CostumerCreation.as_view(), name='create'),
    path('login/', CostumerLogin.as_view(), name='login'),
    path('logout/', CostumerLogout.as_view(), name='logout'),
]

apps/order/urls.py
from django.urls import path

from .views import OrderPayment, OrderDetail, SaveOrder, OrderList


app_name = 'order'

urlpatterns = [
    path('payment/<int:pk>', OrderPayment.as_view(), name='payment'),
    path('save_order/', SaveOrder.as_view(), name='save_order'),
    path('detail/<int:pk>', OrderDetail.as_view(), name='detail'),
    path('list/', OrderList.as_view(), name='list'),
]

apps/product/urls.py
from django.urls import path

from .views import (
    ProductList,
    ProductDetail,
    AddToCart,
    RemoveFromCart,
    Cart,
    Checkout,
    Search,
)


app_name = 'product'

urlpatterns = [
    path('', ProductList.as_view(), name='list'),
    path('<slug>', ProductDetail.as_view(), name='detail'),
    path('addtocart/', AddToCart.as_view(), name='addtocart'),
    path('removefromcart/', RemoveFromCart.as_view(), name='removefromcart'),
    path('cart/', Cart.as_view(), name='cart'),
    path('checkout/', Checkout.as_view(), name='checkout'),
    path('search/', Search.as_view(), name='search'),
]

dataprev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#from apps.product.api.urls import router

urlpatterns = [
    path('', include('apps.product.urls')),
    path('costumer/', include('apps.costumer.urls')),
    path('order/', include('apps.order.urls')),
    path('admin/', admin.site.urls),
    #path('api/v1/', include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/partials/_cart.html
{% load static %}
{% load omfilters %}

<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Image</th>
            <th>Product</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>

        {% for line in cart.values %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{% get_media_prefix %}{{ line.image }}">
            </td>
            <td>
                <a href="{% url 'product:detail' line.slug %}">
                    {{ product.name }}
                </a>
                <a class="ml-3" href="#">
                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                </a>
            </td>
            <td>
                {{ line.variation_name }}
            </td>
            <td>
                {{ line.quantity }}x
            </td>

            {% if line.quantitative_promotional_price %}
            <td>{{ line.quantitative_promotional_price|price_formatted  }}</td>
            {% else %}
            <td>{{ line.quantitative_price|price_formatted  }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
</div>

templates/partials/_footer.html
{% load static %}
{% load omfilters %}

<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1"></span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">By Joscelino Celso de Oliveira</span>
                </div>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js' %}"></script>
<script src="{% static 'assets/custom/js/scripts.js' %}"></script>

templates/partials/_head.html
{% load static %}
{% load omfilters %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">

templates/partials/_messages.html
{% if messages %}
{% load omfilters %}

    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/partials/_nav.html
{% load omfilters %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'product:list' %}">E-commerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'product:list' %}">Home <span class="sr-only">(current)</span></a>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>

            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'order:list' %}">My Orders</a>
                    <a class="dropdown-item" href="{% url 'costumer:create' %}">Update account</a>
                    <a class="dropdown-item" href="{% url 'costumer:logout' %}">Log out</a>
                </div>
            </li>

            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'costumer:create' %}">Sign in</a>
            </li>
            {% endif %}

            {% if request.session.Cart %}
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="{% url 'product:cart' %}">
                        <span class="nav-cart-text mr-1">
                            Cart
                        </span>
                    <span class="nav-cart-count mr-1">
                            <strong>{{ total_quantity_cart }}x</strong>
                        </span>
                    <span class="nav-cart-icon mr-2">
                            <i class="fas fa-shopping-cart"></i>
                        </span>
                </a>
            </li>
            {% endif %}

        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'product:search' %}">
            <input name="term" value="{{ request.GET.term }}" class="form-control mr-sm-2" type="search"
                   placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/partials/_pagination.html
{% load omfilters %}
{% if is_paginated %}

<div class="col mt-3 mb-3">
    <div class="rol">

        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>

    </div>
</div>

{% endif %}