apps/order/urls.py
from django.urls import path

from .views import OrderPayment, OrderDetail, SaveOrder, OrderList


app_name = 'order'

urlpatterns = [
    path('payment/<int:pk>', OrderPayment.as_view(), name='payment'),
    path('save_order/', SaveOrder.as_view(), name='save_order'),
    path('detail/<int:pk>', OrderDetail.as_view(), name='detail'),
    path('list/', OrderList.as_view(), name='list'),
]

dataprev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#from apps.product.api.urls import router

urlpatterns = [
    path('', include('apps.product.urls')),
    path('costumer/', include('apps.costumer.urls')),
    path('order/', include('apps.order.urls')),
    path('admin/', admin.site.urls),
    #path('api/v1/', include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/order/models.py
from django.db import models
from django.contrib.auth.models import User


class Base(models.Model):

    """  Order database registration control """
    registration = models.DateField('Registration data', auto_now_add=True)
    modification = models.DateField('Modification data', auto_now=True)
    active = models.BooleanField('Active', default=True)

    class Meta:
        abstract = True


class Order(Base):

    """ Order database fields """
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    total = models.FloatField()
    total_quantity = models.PositiveIntegerField(verbose_name='total quantity')
    status = models.CharField(
        default='R',
        max_length=1,
        choices=(
            ('A', 'Approved'),
            ('R', 'Registered'),
            ('C', 'Canceled'),
            ('I', 'In approval'),
            ('T', 'In transport'),
            ('D', 'Delivered'),
        )
    )

    def __str__(self):
        return f'Order number: {self.id}'


class ItemOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.CharField(max_length=60)
    product_id = models.PositiveIntegerField()
    variation = models.CharField(max_length=50)
    variation_id = models.PositiveIntegerField()
    price = models.FloatField()
    promotional_price = models.FloatField(default=0)
    image = models.CharField(max_length=2000)

    def __str__(self):
        return f'{self.order}'

    class Meta:
        verbose_name = 'Order item'
        verbose_name_plural = 'Order items'

apps/order/views.py
from django.shortcuts import redirect, render, reverse
from django.views.generic import ListView, DetailView
from django.views import View
from django.contrib import messages

from apps.product.models import Variation
from apps.order.models import Order, ItemOrder
from utils import utils


class DispatchLoginRequiredMixin(View):
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('costumer:create')

        return super().dispatch(*args, **kwargs)


class OrderPayment(DispatchLoginRequiredMixin, DetailView):
    template_name = 'order/payment.html'
    model = Order
    pk_url_kwarg = 'pk'
    context_object_name = 'order'

    def get_queryset(self, *args, **kwargs):
        """ Each user can only see their order """
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(user=self.request.user)
        return qs


class SaveOrder(View):
    template_name = 'order/payment.html'

    def get(self, *args, **kwargs):

        if not self.request.session.get('cart'):
            messages.error(
                self.request,
                'Empty cart.'
            )
            return redirect('product:list')

        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Please, login or create account.'
            )
            return redirect('costumer:create')

        cart = self.request.session.get('cart')
        cart_variation_ids = [v for v in cart]

        variations_db = list(
            Variation.objects.select_related('product').filter(id__in=cart_variation_ids)
        )

        for variations in variations_db:
            vid = variations.id
            inventory = variations.inventory
            cart_qt = cart[vid]['quantity']
            price = cart[vid]['price']
            promotional_price = cart[vid]['promotional_price']

            error_msg_inventory = ''

            if inventory < cart_qt:
                cart[vid]['quantity'] = inventory
                cart[vid]['price'] = inventory * price
                cart[vid]['promotional_price'] = inventory * promotional_price
                error_msg_inventory = 'Some products had inventory changes. ' \
                                      'We reduced the quantities in your initial order.'

                if error_msg_inventory:
                    messages.info(
                        self.request,
                        error_msg_inventory,
                    )
                    self.request.save()
                    return redirect('product:cart')

        total_quantity_cart = utils.total_quantity_cart('cart')
        total_value_cart = utils.cart_total('cart')

        order = Order(
            user=self.request.user,
            total=total_value_cart,
            total_quantity=total_quantity_cart,
            status='C',
        )

        order.save()

        ItemOrder.objects.bulk_create(
            [
                ItemOrder(
                    order=order,
                    product=v['product'],
                    product_id=v['product_id'],
                    variation=v['variation_name'],
                    variation_id=v['variation_id'],
                    price=v['quantitative_price'],
                    promotional_price=v['quantitative_promotional_price'],
                    image=v['image'],
                ) for v in cart.values()
            ]
        )

        context = {
            'total_quantity_cart': total_quantity_cart,
            'total_value_cart': total_value_cart,
        }

        del self.request.session['cart']
        # return render(self.request, self.template_name, context)
        return redirect(
            reverse(
                'order:payment',
                kwargs={
                    'pk': order.pk,
                }
            )
        )


class OrderDetail(DispatchLoginRequiredMixin, DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'order/detail.html'
    pk_url_kwarg = 'pk'


class OrderList(ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'order/list.html'
    paginate_by = 10
    ordering = ['-pk']

apps/order/templates/order/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

apps/order/templates/order/list.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}

        <div class="row">
            <div class="col">
                <h3 class="mb-4">Orders History from {{ user }}</h3>
                <p>Orders history</p>

                <div class="table-responsive">

                    <table class="table table-striped">
                        <tr>
                            <th scope="col">Pedido</th>
                            <th scope="col">Total</th>
                            <th scope="col">Qtd. Itens</th>
                            <th scope="col">Status</th>
                            <th scope="col">Mais detalhes</th>
                        </tr>

                        {% for order in orders %}
                        <tr>
                            <th scope="row">{{ order }}</td>
                            <td>{{ order.total|price_formatted }}</td>
                            <td>{{ order.total_quantity }}</td>
                            <td>{{ order.get_status_display }}</td>
                            <td>
                                <a href="{% url 'order:detail' order.pk %}">
                                    Ver <i class="fas fa-search-plus ml-2"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>

                </div>
            </div>
        </div>

{% include 'partials/_pagination.html' %}

{% endblock %}

apps/order/templates/order/payment.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col mt-3">
        <h3>Choice a payment method</h3>
        <div>
        <p>Payment methods here</p>
        </div>
    </div>
</div>

{% endblock %}

apps/order/templates/order/save_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>