apps/costumer/urls.py
from django.urls import path

from .views import CostumerCreation, CostumerLogin, CostumerLogout

app_name = 'costumer'

urlpatterns = [
    path('', CostumerCreation.as_view(), name='create'),
    path('login/', CostumerLogin.as_view(), name='login'),
    path('logout/', CostumerLogout.as_view(), name='logout'),
]

apps/order/urls.py
from django.urls import path

from .views import OrderPayment, OrderDetail, SaveOrder, OrderList


app_name = 'order'

urlpatterns = [
    path('payment/<int:pk>', OrderPayment.as_view(), name='payment'),
    path('save_order/', SaveOrder.as_view(), name='save_order'),
    path('detail/<int:pk>', OrderDetail.as_view(), name='detail'),
    path('list/', OrderList.as_view(), name='list'),
]

apps/product/api/urls.py
from .apiviews import ProductAPIViewSet, VariationAPIViewSet
from rest_framework.routers import SimpleRouter

router = SimpleRouter()
router.register('product', ProductAPIViewSet)
router.register('variations', VariationAPIViewSet)

apps/product/urls.py
from django.urls import path

from .views import (
    ProductList,
    ProductDetail,
    AddToCart,
    RemoveFromCart,
    Cart,
    Checkout,
    Search,
)


app_name = 'product'

urlpatterns = [
    path('', ProductList.as_view(), name='list'),
    path('<slug>', ProductDetail.as_view(), name='detail'),
    path('addtocart/', AddToCart.as_view(), name='addtocart'),
    path('removefromcart/', RemoveFromCart.as_view(), name='removefromcart'),
    path('cart/', Cart.as_view(), name='cart'),
    path('checkout/', Checkout.as_view(), name='checkout'),
    path('search/', Search.as_view(), name='search'),
]

dataprev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#from apps.product.api.urls import router

urlpatterns = [
    path('', include('apps.product.urls')),
    path('costumer/', include('apps.costumer.urls')),
    path('order/', include('apps.order.urls')),
    path('admin/', admin.site.urls),
    #path('api/v1/', include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/product/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify

import os
from PIL import Image

from utils import utils


class Base(models.Model):

    """ Product database registration control """
    registration = models.DateField('Registration data', auto_now_add=True)
    modification = models.DateField('Modification data', auto_now=True)
    active = models.BooleanField('Active', default=True)

    class Meta:
        abstract = True


class Product(Base):

    """ Product database fields """
    name = models.CharField(verbose_name='Name', max_length=60)
    short_description = models.TextField(verbose_name='Short description', max_length=60)
    long_description = models.TextField(verbose_name='Long description')
    image = models.ImageField(verbose_name='Image', upload_to='product_images/%Y/%m/', blank=True, null=True)
    slug = models.SlugField(verbose_name='Slug', unique=True, blank=True, null=True, help_text="Don't need to type")
    price = models.FloatField(verbose_name='Price')
    promotional_price = models.FloatField(verbose_name='Promotional price', default=0)
    product_type = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variable'),
            ('S', 'Simple'),
        )
    )

    def get_formatted_price(self):
        """ Return the formatted price to use in display admin """
        return utils.price_formatted(self.price)

    get_formatted_price.short_description = 'Price'

    def get_formatted_promotional_price(self):
        """ Return the formatted promotional price to use in display admin """
        return utils.price_formatted(self.promotional_price)

    get_formatted_promotional_price.short_description = 'Promotional Price'

    @staticmethod
    def resize_image(img, new_width=600):

        """ Resizing the original images from upload """
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            img_pil.close()
            return

        new_height = round((new_width * original_height) / original_width)

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=60,
        )

    def save(self, *args, **kwargs):
        if not self.slug:
            """ Automated slug """
            slug = f'{slugify(self.name[:40])}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 600

        if self.image:
            self.resize_image(self.image, max_image_size)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return self.name


class Variation(models.Model):
    product = models.ForeignKey(Product, verbose_name='Product', related_name='variations', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='variation', max_length=50, blank=True, null=True)
    price = models.FloatField(verbose_name="Price")
    promotional_price = models.FloatField(verbose_name='Promotional price', default=0)
    inventory = models.PositiveIntegerField(default=1)

    class Meta:
        unique_together = ['product', 'name']
        ordering = ['pk']

    def __str__(self):
        return self.name or self.product.name

apps/product/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.contrib import messages
from django.db.models import Q

from apps.costumer.models import CostumerAddress
from .models import Product, Variation


class ProductList(ListView):
    model = Product
    template_name = 'product/list.html'
    context_object_name = 'products'
    paginate_by = 9
    ordering = ['-pk']


class Search(ProductList):
    def get_queryset(self, *args, **kwargs):
        term = self.request.GET.get('term') or self.request.session['term']
        qs = super().get_queryset(*args, **kwargs)

        if not term:
            return qs

        qs = qs.filter(
            Q(name__icontains=term) |
            Q(short_description=term) |
            Q(long_description=term)
        )
        self.request.session.save()

        return qs


class ProductDetail(DetailView):
    model = Product
    template_name = 'product/detail.html'
    context_object_name = 'product'
    slug_url_kwarg = 'slug'


class AddToCart(View):

    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('product:list')
        )
        variation_id = self.request.GET.get('vid')
        print(variation_id)

        if not variation_id:
            messages.error(
                self.request,
                'Product not found',
            )
            return redirect(http_referer)

        variation = get_object_or_404(Variation, id=variation_id)
        inventory_variation = variation.inventory
        product = variation.product
        product_id = product.pk
        product_name = product.name
        variation_name = variation.name or ''
        price = variation.price
        promotional_price = variation.promotional_price
        quantity = 1
        slug = product.slug
        image = product.image

        if image:
            image = image.name
        else:
            image = ''

        if variation.inventory < 1:
            messages.error(
                self.request,
                'Unavailable',
            )
            return redirect(http_referer)

        if not self.request.session.get('cart'):
            self.request.session['cart'] = {}
            self.request.session.save()

        cart = self.request.session['cart']

        if variation_id in cart:
            cart_quantity = cart[variation_id]['quantity']
            cart_quantity += 1

            if inventory_variation < cart_quantity:
                messages.warning(
                    self.request,
                    f'There is no {cart_quantity} units for {product_name}. Added {inventory_variation} in the cart.'
                )
                cart_quantity = inventory_variation

            cart[variation_id]['quantity'] = cart_quantity
            cart[variation_id]['quantitative_price'] = price * cart_quantity
            cart[variation_id]['quantitative_promotional_price'] = promotional_price * cart_quantity

        else:
            cart[variation_id] = {
                'product': product,
                'product_id': product_id,
                'product_name': product_name,
                'variation_name': variation_name,
                'variation_id': variation_id,
                'quantitative_price': price,
                'quantitative_promotional_price': promotional_price,
                'quantity': 1,
                'slug': slug,
                'image': image,
            }

        self.request.session.save()
        messages.success(
            self.request,
            f'Product: {product_name} added in the cart with success'
        )
        return redirect(http_referer)


class RemoveFromCart(View):
    def get(self, *args, **kwargs):
        http_referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('product:list')
        )
        variation_id = self.request.GET.get('vid')

        if not variation_id:
            return redirect(http_referer)

        if not self.request.session.get('cart'):
            return redirect(http_referer)

        if variation_id not in self.request.session['cart']:
            return redirect(http_referer)

        cart = self.request.session['cart'][variation_id]

        messages.success(
            self.request,
            f'Product {cart["product_name"]} {cart["variation_name"]} was removed from your cart.'
        )

        del self.request.session['cart'][variation_id]
        self.request.session.save()

        return redirect(http_referer)


class Cart(View):

    def get(self, *args, **kwargs):
        context = {
            'cart': self.request.session.get('cart', {}),
        }
        return render(self.request, 'product/cart.html', context)


class Checkout(View):

    def get(self, *args, **kwargs):

        if not self.request.user.is_authenticated:
            return redirect('costumer:create')

        profile = CostumerAddress.objects.filter(user=self.request.user).exists()

        if not profile:
            messages.error(
                self.request,
                'User without profile.',
            )
            return redirect('costumer:create')

        if not self.request.session.get('cart'):
            messages.error(
                self.request,
                'Cart empty',
            )
            return redirect('product:list')

        context = {
            'user': self.request.user,
            'cart': self.request.session['cart'],
        }

        return redirect(self.request, 'product/checkout.html', context)

apps/product/templates/product/cart.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}

{% if request.session.cart %}

<main class="container mt-4 mb-4">
    <div class="row mt-3">
        <div class="col">
            <h3>cart</h3>
            <p class="lead">The products, quantities and prices you have chosen.</p>

            {% include 'partials/_cart.html' %}
        </div>
    </div>



    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>cart total</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total</td>
                        <td>{{ cart|cart_total }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">
            {% if request.user.is_authenticated %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'product:checkout' %}">
                Ending order
            </a>
            {% else %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'costumer:create' %}'">
                Ending order
            </a>
            {% endif %}
        </div>
    </div>

    {% else %}
    <div class="row mt-3">
        <div class="col">
            <p class="lead">empty shopping cart</p>
        </div>
    </div>

    {% endif %}
    {% endblock %}

apps/product/templates/product/checkout.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}

 <div class="row mb-5">
            <div class="col-lg">
                <h2>Order summary</h2>

                <p class="lead">User data</p>
                <p>If you need to edit, <a href="{% url 'costumer:create' %}">click here</a></p>
                <dl class="row">
                    <dt class="col-lg-2">Name:</dt>
                    <dd class="col-lg-4">{{ user.first_name }}</dd>
                    <dt class="col-lg-2">{{ user.last_name }}</dt>


                    <dt class="col-lg-2">Age:</dt>
                    <dd class="col-lg-4">{{ user.profile.age }}</dd>
                    <dt class="col-lg-2">Birth date:</dt>
                    <dd class="col-lg-4">{{ user.profile.birth_date }}</dd>

                    <dt class="col-lg-2">CPF:</dt>
                    <dd class="col-lg-4">{{ user.profile.cpf }}</dd>
                    <dt class="col-lg-2">E-mail:</dt>
                    <dd class="col-lg-4">{{ user.email }}</dd>
                </dl>

                <p class="lead">Address data</p>
                <p>If you need to edit, <a href="{% url 'costumer:create' %}">click here</a></p>
                <dl class="row">
                    <dt class="col-lg-2">Address:</dt>
                    <dd class="col-lg-4">{{ user.profile.address }}</dd>
                    <dt class="col-lg-2">Number:</dt>
                    <dd class="col-lg-4">{{ user.profile.number }}</dd>

                    <dt class="col-lg-2">Adjunct address:</dt>
                    <dd class="col-lg-4">{{ user.profile.adjunct_address }}</dd>

                    <dt class="col-lg-2">City:</dt>
                    <dd class="col-lg-4">{{ user.profile.city }}</dd>
                    <dt class="col-lg-2">State:</dt>
                    <dd class="col-lg-4">{{ user.profile.state }}</dd>

                    <dt class="col-lg-2">ZIP Code:</dt>
                    <dd class="col-lg-4">{{ user.profile.zip_code }}</dd>
                </dl>
            </div>
        </div>



        <div class="row mt-3">
            <div class="col">
                <h3>Cart</h3>
                <p class="lead">The products, quantities and prices you have chosen.</p>
                {% include 'partials/_cart.html' %}
            </div>
        </div>

        <div class="row mt-3">
            <div class="col">
                <p class="lead  text-center"><span class="font-weight-bold">Cart Total:</span>{{ cart|cart_totals|price_formatted}}</p>
            </div>
        </div>


        <div class="row mt-3">
            <div class="col">
                <a class="btn btn-block btn-primary btn-lg" href="{% url 'product:save_order' %}">
                    Place order and pay.
                </a>
            </div>
        </div>


{% endblock %}

apps/product/templates/product/detail.html
{% extends 'base.html' %}
{% load omfilters %}

{% block title %}{{ product.name }} | {% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg">
        <div class="row no-gutters">
            <div class="col-lg-12">
                {% if product.image %}
                <img class="img-fluid" src="{{ product.image.url }}">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg">
        <div class="mt-4 mt-lg-0">
            <h1 class="h2">{{ product.name }}</h1>
            <p class="lead">{{ product.short_description }}</p>
            <p class="lead">
                {% if product.promotional_price %}
                <span id="variation-promotional-price" class="lead product-price">
                    {{ product.promotional_price|price_formatted}}
                </span>
                <span id="variation-price" class="lead product-old-price text-muted">
                    {{ product.price|price_formatted }}
                </span>
                {% else %}
                <span id="variation_price" class="lead product-price">
                    {{ product.price|price_formatted }}
                </span>
                {% endif %}
            </p>

            <form action="{% url 'product:addtocart' %}" id="form-add-to-cart">
                <div class="form-group">
                    <select id="select-variations" name="vid" class="form-control form-control-lg">

                        {% for variation in product.variations_set.all %}

                        {% if variation.promotional_price %}
                        <option data-preco="{{ variation.price|price_formatted }}"
                            data-preco-promocional="{{ variation.promotional_price|price_formatted }}"
                            value="{{ variation.pk }}">
                            {% if variation.name %}
                            {{ variation.name }}
                            {% else %}
                            {{ variation }}
                            {% endif %}
                        </option>
                        {% else %}
                        <option data-preco="{{ variation.price|price_formatted }}" value="{{ variation.pk }}">
                            {% if variation.name %}
                            {{ variation.name }}
                            {% else %}
                            {{ variation }}
                            {% endif %}
                        </option>
                        {% endif %}

                        {% endfor %}
                    </select>
                </div>

                <div class="text-left">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Add to cart
                    </button>
                </div>

            </form>


        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 class="text-center">{{ product.name }}</h2>
            {{ product.long_description|linebreaks }}
        </div>
    </div>
</div>


{% endblock %}

apps/product/templates/product/list.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card-columns">

                {% for product in products %}

                <div class="card">

                    {% if product.image %}
                    <a href="{% url 'product:detail' product.slug %}">
                        <img class="card-img-top" src="{{ product.image.url }}"
                             alt="{{ product.name }}">
                    </a>
                    {% endif %}

                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.short_description }}</p>
                        <div class="container product-price-block text-center">

                                {% if product.promotional_price %}
                                    <span class="product-price">
                                        {{ product.promotional_price|price_formatted }}
                                    </span>
                                    <span class="product-old-price text-muted">
                                        {{ product.price|price_formatted }}
                                    </span>
                                {% else %}
                                    <span class="product-price">
                                        {{ product.price|price_formatted }}
                                    </span>
                                {% endif %}
                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-top-light-custom text-center">
                        <a href="{% url 'product:detail' product.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            Buy
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
<div class="row mt-3" >
    <div class="col">
        {% include 'partials/_pagination.html' %}
    </div>
</div>

{% endblock %}